name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGETAG: "docker.pkg.github.com/${{github.repository}}/demo:latest"

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file 'Dockerfile' --tag "${IMAGETAG}"
    - name: Test the Docker image
      run: docker run --rm "${IMAGETAG}" uname -a
    - name: Deploy to GPR
      run: 
        docker login -u matthewrmshin --password-stdin 'docker.pkg.github.com' <<<'{{secrets.GITHUB_TOKEN}}'
        docker push "${IMAGETAG}"
