name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Conda
      uses: matthewrmshin/conda-action@master
      with:
        args: conda env update -p "${CONDA_PREFIX}" -f ./requirements.yml
    - name: Lint with flake8
      run: |
        flake8 . --show-source --statistics
    - name: Test with pytest
      run: |
        env PYTHONPATH=$PWD pytest
